### ISSUE TITLE
encoding issues in file names

### ISSUE THREAD

**Issue by laerm0** [source-foundry/glyph-filter-lists#3]
Hello –

Just cloned this repo to my Mac and it looks like a few of the names have encoding issues.

```
CofÃ¡n.txt
MÄori.txt
OnÄ•ipÅt.txt
VÃµro.txt
```

The same issues are found in the file content as well.

**Comment by chrissimpkins** [comment]
Thanks for the report! Can you point to the files that this affects Micah?

**Comment by laerm0** [comment]
The ones I listed. No idea what they're supposed to say (I can guess `MÄ�ori.txt` should be `Māori.txt`).

**Comment by chrissimpkins** [comment]
Apologies! Misread them as glyph names.  I will take a look.   Those come from the Underware collection as I recall.

**Comment by chrissimpkins** [comment]
I fixed all of these path names Micah.  The files were parsed by a robot :) and I missed this.  If you happen to ever need the writing system name data from Underware down the road, it is available here:

http://www.underware.nl/latin_plus/languages/

Thanks again for this report!

**Comment by chrissimpkins** [comment]
Also pushed this as a new v2.0.1. release on the repository.
